theme: jekyll-theme-minimal
title: [Bernardo Moreno Peniche]
description: [I am a medical anthropologist studying how diseases, environments, and borders shape one another]
logo: ./photo.png
show_downloads: false

